### ISSUE TITLE
Как насчет поставить fill-column равным 79/80?

### ISSUE THREAD

**Issue by ghost** [NoobsEnslaver/scheme_book#2]
Сейчас читается мягко говоря не очень. У вас широкий экран? Просто я
привык consoom'ить всё в ширине 79, вот и немного больно,
visual-line-mode не помогает.

**Comment by NoobsEnslaver** [comment]
Да, широкоформатный экран, и 120 символов в ширину вмещает легко, как и у 99% людей сегодня. Если вы хотите серьезно законтрибьютить и это вас удерживает - создайте отдальный файл, выставье там нужную вам ширину колонки, а потом просто заинклюдьте его в основной index.org, либо я могу потом заняться форматированием всего под один стиль. Здесь речь идёт только про удобство перевода, для чтения - файл можно скомпилировать и ширина колонки исходника там не будет иметь значения.
